### PR TITLE
Better coverage of 'twice a day' prescription texts for the DOAC meds

### PR DESCRIPTION
**Pull request by sinnottj-rse**
I've added some new regexps to capture variations on the 'twice a day' prescription for DOAC meds, which the existing regexp didn't pick up.

Notes: 

- I chose not to try tweaking the existing regexp, as didn't think it was worth the risk of breaking any part of it.
- I intentionally kept the new regexps simple, rather than trying to combine them

### CODE REVIEW

**Comment by rw251** [comment]
Thanks for this. Can you do the following test to confirm that the new regexes don't incorrectly capture things that are 1 a day:
- Get all the instructions ordered by count descending
- Run the "1" regexes against them, to filter the list to just those that currently match 1 a day
- Run the new "2" regexes against this filtered list and review any where the "2" regex matches. Hopefully this will either be none - or just things that were previously incorrectly matching 1 a day.

In general we probably need a way to automate this process so we can view a report - but I'll raise a ticket and pick that up separately.

**Comment by sinnottj-rse** [comment]
I've done some pretty exhaustive testing this afternoon, albeit only against the dev database.  My findings were:

1) The 3 new regexes _don't_ incorrectly match anything currently classified as 1/day
2) Neither do they match with anything that the existing regexes don't currently match and correctly default to 1/day
3) They _do_ incorrectly match against some lines that should be 3/day. However, these lines aren't matched by the existing 3/day regex and so currently default to 1/day. As such classifying them as 2/day is an improvement ...

**Comment by sinnottj-rse** [comment]
Also I'm happy to test further against the live data if you want (and can supply me with it!)

**Comment by sinnottj-rse** [comment]
I've added the extra regexes covering 8,6,5,4 & 3 a day. They've been tested on the live prescription data, and I'm confident they are not breaking any existing classifications.

**Pull request merged**
